base:
    project: Crop disease detection

raw_data:
    data_src: data_source

load_data:
    num_classes: 2
    row_data: data_soure
    preprocessed_data: data/processed
    full_path: dlproject/data_source

train :
    split_ratio: 0.80

model:
    name: CNN
    trainable: False
    train_path: data/processed/train
    test_path: data/processed/test
    optimizer: adam   
    loss: categorical_crossentropy  
    metrics: ["accuracy"]
    epochs: 1
    image_size: [255,255]
    # batch_size:32
    sav_dir: models/trained.h5
 

model_dir: models

mlflow_config:
    artiact_dir: artifacts
    experiment_name: CropDiseaseDetection
    run_name: mlops
    registered_model_name: CropDiseaseDetectionModel
    remote_server_uri: http://127.0.0.1:5000
    